### ISSUE TITLE
郭子路

### ISSUE THREAD

**Issue by Karlguo** [LiuZeyu-sjtu/BlackJack#1]
优点有很多
1. 动用全局变量，方便运算。
2. 运用try catch语句进行判断。
3. 多个子程序简化了程序。
问题不是很大
1. 也是因为全局变量，电脑进行游戏的时候会输出玩家的牌+电脑的牌（如玩家抽到红桃10，方片10，电脑抽到红桃9，黑桃8，显示电脑抽到的是“红桃10，方片10，红桃9，黑桃8”），这可能是由于没有refresh全局变量造成的。

**Comment by LiuZeyu-sjtu** [comment]
已修正错误。感谢指出！
